Maeeveee/Sistem-Manajemen-Pelaporan-dan-Perbaikan-Fasilitas-Kampus

app/Http/Livewire/ManajemenFasilitas.php, app/Http/Livewire/ManajemenGedung.php, app/Models/Fasilitas.php, app/Models/Gedung.php, app/Models/Ruangan.php, database/migrations/2025_05_21_094027_create_fasilitas_table.php, database/migrations/2025_05_21_094030_create_gedung_table.php, database/migrations/2025_05_21_094147_create_ruangan_table.php, resources/views/livewire/manajemen-fasilitas.blade.php, resources/views/livewire/manajemen-gedung.blade.php
Mengupdate uppercase untuk kode gedung dan kode fasilitas. Merubah form menambah fasilitas menjadi pilih gedung -> pilih lantai -> pilih ruangan -> menambahkan fasilitas
=> Update Manajemen Gedung & Manejemn Fasilitas

app/Http/Livewire/Components/Forms/FormKerusakanFasilitas.php, resources/views/livewire/components/forms/form-kerusakan-fasilitas.blade.php, resources/views/livewire/dashboard-sarpras.blade.php, resources/views/livewire/dashboard-teknisi.blade.php
update warna dari status dan membenahkan isi dari laporan
=> update warna status & laporan kerusakan

app/Http/Livewire/Components/Forms/FormKerusakanFasilitas.php, app/Models/LaporanKerusakan.php, database/migrations/2025_05_24_134103_create_laporan_kerusakan_table.php, resources/views/livewire/components/forms/form-kerusakan-fasilitas.blade.php
Menyambungkan form dengan database dan membuat database untuk menyimpan form
=> Menyambungkan form laporan dengan database

resources/views/layouts/sidenav.blade.php, resources/views/livewire/landing-page.blade.php
- sudah beres masalah dropdown sidenav 
- menyeragamkan tulisan button di landing page (Masuk & Daftar)
=> fix dropdown sidenav & change button placeholder on landing page

resources/views/livewire/components/forms/form-kerusakan-fasilitas.blade.php, resources/views/livewire/manajemen-fasilitas.blade.php, resources/views/livewire/manajemen-gedung.blade.php
memperbaiki breadcrumb yang hanya ada 1 parent
=> fixing breadcrumb on fasilitas & gedung

app/Http/Livewire/ManajemenKriteriaFasilitas.php, app/Models/Kriteria.php, app/Models/SubKriteria.php, database/migrations/2025_05_30_123950_create_kriterias_table.php, database/migrations/2025_05_30_124103_create_sub_kriterias_table.php, database/seeders/KriteriaSeeder.php, database/seeders/SubKriteriaSeeder.php, resources/views/livewire/manajemen-kriteria-fasilitas.blade.php
Merubah pada database menjadi 2 yaitu: Kriteria dan Subkriteria
=> Perbaikan pada manajemen kriteria

resources/views/livewire/manajemen-kriteria-fasilitas.blade.php, resources/views/livewire/manajemen-subkriteria.blade.php
=> perbaikan kolom jenis pada manajemen kriteria dan subkriteria

resources/views/layouts/sidenav.blade.php
menambahkan routing menu untuk setiap role user
=> update routing menu for each user

resources/views/livewire/manajemen-kriteria-fasilitas.blade.php
memperbaiki tampilan yang nantinya bobot bisa di gabungkan dengan data table ahp yang dikerjakan kamila
=> memperbaiki tampilan bobot% untuk pembobotan ahp (kamila)

app/Http/Livewire/PerhitunganSpk.php
mempersingkat kode perhitungan topsis
=> refactor Topsis method code

app/Http/Livewire/PerhitunganKriteria.php
membetulkan perhitungan AHP karena berbeda tuitik
=> refactor perhitungan AHP

app/Http/Livewire/PerhitunganSpk.php, resources/views/livewire/perhitungan-spk.blade.php
mengubah urutan susunan tabel pada perhitungan spk dan menambahkan button reset untuk perhitungan spk
=> reordering SPK table and add reset button for calculate SPK

app/Http/Livewire/Components/Forms/FormKerusakanFasilitas.php, app/Http/Livewire/DetailHistoryLaporan.php, app/Http/Livewire/HistoryLaporan.php, app/Http/Livewire/LihatDetailSarpras.php, resources/views/livewire/components/forms/form-kerusakan-fasilitas.blade.php, resources/views/livewire/detail-history-laporan.blade.php, resources/views/livewire/history-laporan.blade.php, resources/views/livewire/lihat-detail-sarpras.blade.php
Merivisi yang awalnya user yang input kriteria kerusakan sekarang diganti hanya sarpras yang menginputkan
=> Revisi untuk menginputkan kriteria

resources/views/livewire/lihat-detail-sarpras.blade.php
memperbaiki typo pada tabel frekuensi karena sudah diinput masih bisa dirubah tapi sekarang sudah aman
=> update lihat detail sarpras

app/Http/Livewire/PerhitunganKriteria.php, resources/views/livewire/perhitungan-kriteria.blade.php
merubah cara menginput matriks perbandingan pada perhitungan kriteria
=> update input method to calculate criteria

app/Http/Livewire/PerhitunganKriteria.php, resources/views/livewire/perhitungan-kriteria.blade.php
=> add sweet alert for calculate criteria

app/Http/Livewire/Notifications.php, resources/views/livewire/notifications.blade.php
membuat notifikasi menjadi realtime agar ketika ada data baru notif bisa langsung menampilkannya dan ketika laporan di klik akan mengarah ke page laporan untuk setiap role
=> update realtime notification and make href dynamic on every role

resources/views/livewire/perhitungan-spk.blade.php
perbaikan modal aksi proses dan detail
=> perbaikan pada modal aksi perhitungan spk ke teknisi

app/Http/Livewire/Dashboard.php, resources/views/dashboard.blade.php
memperbaiki data yang akan ditampilkan pada dashboard
=> update data serve on dashboard

app/Http/Livewire/DashboardTeknisi.php, app/Models/LaporanKerusakan.php, resources/views/livewire/dashboard-teknisi.blade.php, resources/views/livewire/perhitungan-spk.blade.php
perbaikan struktur kode di controller dan di view livewire dashboard teknisi dan perbaikan untuk source foto di modal detail perhitungan spk
=> perbaikan struktur controller dan view dashboard teknisi dan perbaikan modal spk

app/Http/Livewire/Profile.php, app/Http/Livewire/ProfilePhotoUpload.php, app/Models/User.php, resources/views/layouts/base.blade.php, resources/views/layouts/topbar.blade.php, resources/views/livewire/profile-photo-upload.blade.php, resources/views/livewire/profile.blade.php
Update Manajemen Profile by Naditya
=> Update Manajemen Profile

app/Http/Livewire/ManajemenPengguna.php, resources/views/vendor/pagination/bootstrap-5.blade.php
=> fix pagination

app/Http/Livewire/VerifikasiPerbaikan.php, resources/views/layouts/app.blade.php, resources/views/layouts/sidenav.blade.php, resources/views/livewire/dashboard-sarpras.blade.php, resources/views/livewire/verifikasi-perbaikan.blade.php, routes/web.php
membuat tampilan untuk verifikasi laporan
=> add report verification page

resources/views/layouts/base.blade.php
=> fix modal not load on manajemen pengguna

app/Http/Livewire/ManajemenPengguna.php
=> solve regist eror

resources/views/livewire/history-laporan.blade.php
menambahkan kolom dan foto perbaikan
=> perbaikan pada history laporan

app/Http/Livewire/RiwayatPerbaikan.php, resources/views/layouts/app.blade.php, resources/views/layouts/sidenav.blade.php, resources/views/livewire/riwayat-perbaikan.blade.php, routes/web.php
penambahan menu dan tampilan di teknisi
=> menambahkan menu dan tampilan riwayat perbaikan teknisi

resources/views/livewire/history-laporan.blade.php
=> (user) fixing user table after merging with branch

resources/views/dashboard.blade.php
=> (all) missing something

resources/views/livewire/perhitungan-kriteria.blade.php
=> (sarpras) update option on criteria
